tags:
- name: customers
  description: customers API

paths:
# [GET] customers
  /customers/profile:
    get:
      tags:
      - customers
      summary: Get Customer by id
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] /signup
  /signup:
    post:
      tags:
      - customers
      summary: Register Customer
      parameters:
      - name: body
        in: body
        description: Customer Data
        required: true
        schema:
          $ref: '#/definitions/customersRegister'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
# [PUT] customers
  /customers/update:
    put:
      tags:
      - customers
      summary: Update Customer By Id
      parameters:
      - name: body
        in: body
        description: Customer Data
        required: true
        schema:
          $ref: '#/definitions/customersUpdate'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] customers
  /customers/delete:
    delete:
      tags:
      - customers
      summary: Delete Customer By Id
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
# definitions
definitions:
  customersRegister:
    type: object
    required:
        - name
        - email
        - password
    properties:
      name:
        type: string
        description: customer name
      email:
        type: string
        description: customer Email
      password:
        type: string
        description: customer Password
  customersUpdate:
    type: object
    properties:
      name:
        type: string
        description: new name
      password:
        type: string
        description: new Password

schemes:
 - https
 - http
